### ISSUE TITLE
Enabling loading XML from directory?

### ISSUE THREAD

**Issue by seckin206** [WASdev/standards.jsr352.jbatch#38]
Hi,

How can I enable loading job XMLs from a directory? I know there are two versions of the XML loader, but I couldn't figure out how to do it using batch-service.properties

**Comment by BrentDouglas** [comment]
Afaict, the RI doens't have a built in for it. You could implement `com.ibm.jbatch.spi.services.IJobXMLLoaderService` where you load the job from a dir and then add `JOBXML_LOADER=your.impl.ClassName` to `batch-services.properties`.

**Comment by BrentDouglas** [comment]
Nope, I take that back, it does ha a dir loader. Add  `JOBXML_LOADER=com.ibm.jbatch.container.services.impl .DirectoryJobXMLLoaderServiceImpl` in `batch-services.properties` and you should be right.

**Comment by seckin206** [comment]
I should include the line in my batch applications META-INF/services/batch-services.properties file, am i right?

**Comment by BrentDouglas** [comment]
Hmm it looks like you would have to edit the batch-services.properties from the jbatch jar, which seems pretty useless for what you are doing. You can however provide this info using two system properties instead of editing the jar:
`com.ibm.jbatch.spi.ServiceRegistry.JOBXML_LOADER=com.ibm.jbatch.container.services.impl.DirectoryJobXMLLoaderServiceImpl` and `com.ibm.jbatch.jsl.directory=/path/to/your/xmls`

**Comment by seckin206** [comment]
Well, tried but not working. I still get the same error FileNotFound under META-INF/batch-jobs I guess which indicates that it is not looking for the directory I put.

If you wanna reprocude my setup:
-Dcom.ibm.jbatch.jsl.directory="D:/"
Glassfish 4.1 for application container

**Comment by BrentDouglas** [comment]
Could you post a stack trace? Also shouldn't that be `D:\`?

**Comment by seckin206** [comment]
I will as soon as possible.

**Comment by seckin206** [comment]
Warning:   StandardWrapperValve[PlaygroundMain]: Servlet.service() for servlet PlaygroundMain threw exception
javax.batch.operations.JobStartException: com.ibm.jbatch.container.exception.BatchContainerRuntimeException: java.io.FileNotFoundException: Cannot find an XML file under META-INF/batch-jobs/ with the following name ExternalBatchJob.xml
	at com.ibm.jbatch.container.api.impl.JobOperatorImpl.start(JobOperatorImpl.java:90)
	at org.savasci.honeybadger.jobrunners.DefaultJobRunner.runJob(DefaultJobRunner.java:21)
	at org.savasci.playground.PlaygroundMain.processRequest(PlaygroundMain.java:60)
	at org.savasci.playground.PlaygroundMain.doGet(PlaygroundMain.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.ibm.jbatch.container.exception.BatchContainerRuntimeException: java.io.FileNotFoundException: Cannot find an XML file under META-INF/batch-jobs/ with the following name ExternalBatchJob.xml
	at com.ibm.jbatch.container.services.impl.DelegatingJobXMLLoaderServiceImpl.loadJobFromBatchJobs(DelegatingJobXMLLoaderServiceImpl.java:99)
	at com.ibm.jbatch.container.services.impl.DelegatingJobXMLLoaderServiceImpl.loadJSL(DelegatingJobXMLLoaderServiceImpl.java:70)
	at com.ibm.jbatch.container.api.impl.JobOperatorImpl.startInternal(JobOperatorImpl.java:112)
	at com.ibm.jbatch.container.api.impl.JobOperatorImpl.start(JobOperatorImpl.java:86)
	... 33 more
Caused by: java.io.FileNotFoundException: Cannot find an XML file under META-INF/batch-jobs/ with the following name ExternalBatchJob.xml
	... 37 more

**Comment by seckin206** [comment]
https://gist.github.com/seckin206/2e44b8bf4fd86fabf2f2

**Comment by seckin206** [comment]
![screenshot from 2015-09-10 12 39 25](https://cloud.githubusercontent.com/assets/972671/9786260/080e01c8-57b9-11e5-8610-19cbad06ddee.png)

**Comment by scottkurz** [comment]
The property name is just "JOBXML_LOADER_SERVICE" not the more nicely qualified "com.ibm.jbatch.spi.ServiceRegistry.JOBXML_LOADER".

Well that's kind of ugly.  No one's pushed on this at all in a GF environment so we hadn't thought to make this more nicely configurable.

Also I'm not sure versions of Glassfish this first was integrated with, though I imagine it's been in nightly builds for awhile now.

Please see if that helps.

**Comment by BrentDouglas** [comment]
Oh, yeah I see now. I misread this line as being the literal property:
https://github.com/WASdev/standards.jsr352.jbatch/blob/fc09f8dec9826ca56981fba2dbd43c1d6c411077/com.ibm.jbatch.spi/src/main/java/com/ibm/jbatch/spi/ServiceRegistry.java#L160

**Comment by seckin206** [comment]
I changed the line into this : 
-DJOBXML_LOADER_SERVICE=com.ibm.jbatch.container.services.impl.DirectoryJobXMLLoaderServiceImpl

Still getting the same error.

**Comment by scottkurz** [comment]
Hmm... can you collect server logs in GF with:

   com.ibm.jbatch.container.level=FINEST 

This seems to be the latest hit on how to do that in general:
http://docs.oracle.com/cd/E18930_01/html/821-2416/abluk.html

**Comment by seckin206** [comment]
https://gist.github.com/seckin206/2c9dc64c34fc9ec5c37e

Isolated run, rather than JVM Options, I now added the respective options to "System Properties". No changes in behaviour.

**Comment by seckin206** [comment]
![screenshot from 2015-09-11 00 31 29](https://cloud.githubusercontent.com/assets/972671/9802681/7eb26d06-581c-11e5-943a-3959d93c8f82.png)

**Comment by seckin206** [comment]
BTW, you have mentioned about JSL_DIR here: 

http://stackoverflow.com/questions/19904750/jsr-352-dynamic-job-loading

**Comment by scottkurz** [comment]
I'm sorry.  @BrentDouglas you were right.

The JVM property should be:

***-Dcom.ibm.jbatch.spi.ServiceRegistry.JOBXML_LOADER=com.ibm.jbatch.container.services.impl.DirectoryJobXMLLoaderServiceImpl***

So @seckin206, can you please go back to that property value and collect the same trace?   (Hopefully we have enough logging in this code for this to be useful. Let's give it a shot.)

FWIW, I'd gotten confused between the SPI properties and the JVM system properties.

As you see here:

https://github.com/WASdev/standards.jsr352.jbatch/blob/00a487cdde32a7477263dd4b659d9470b5ed8deb/com.ibm.jbatch.container/src/main/java/com/ibm/jbatch/container/servicesmanager/ServicesManagerImpl.java#L105-L108

the sequence is to configure with the properties files embedded in the JAR, then override with the SPI, then override again with the JVM props.   In the SPI, we use shorter prop names, which has a logic to it.

And btw, I didn't have any extra information in that SO post.  I was just offering to help walk through it like we're doing now.

**Comment by seckin206** [comment]
This issue is no longer valuable for me, I hope discussion so far can help the readers in future.
